### ISSUE TITLE
ListView.setAdapter error

### ISSUE THREAD

**Issue by NyeinEi** [Yalantis/FlipViewPager.Draco#17]
Cannot add BaseFlipAdapter in ListView.setAdapter() method. please help!!!
![capture](https://cloud.githubusercontent.com/assets/13792658/15067744/304cdfa8-13a5-11e6-8f42-91b2e2b0cb96.PNG)

**Comment by majithg** [comment]
hey... I have fixed man... do like this...
1. go to here...
public FriendsAdapter(Context context, List<Friend> items, FlipSettings settings, CloseListener closeListener) {...}
and remove the "CloseListener closeListener" paframeter.
2. go to build.gradle(Module: app)...
then you should declare this one..
compile 'com.yalantis:flipviewpager:1.0.0' instead of  compile project(':flipviewpager')
that's all... 
contact me via: majithg@gmail.com
skype: aka_majith

**Comment by TeeRawk** [comment]
Fixed
